spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
    url: jdbc:mysql://localhost:3306/l_blog?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    #Druid
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 100MB
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    username: 用户名
    password: 密码
  data:
    elasticsearch:
      cluster-name: my-es6
      cluster-nodes: 127.0.0.1:9301,127.0.0.1:9302,127.0.0.1:9303
      repositories:
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.lpepsi.vblog.vdo
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
#  params: count=countSql
logging:
  level:
    top.lpepsi.vblog.dao: debug